interface ReceiptData {
  id: string;
  date: string;
  customer_name: string;
  customer_phone?: string;
  service_name: string;
  price: number;
  payment_status: string;
  brand_name?: string;
}

export const generateProfessionalReceipt = async (data: ReceiptData) => {
  // Dynamic imports to prevent Next.js SSR "window is not defined" crashes
  const { jsPDF } = await import("jspdf");
  await import("jspdf-autotable");
  
  const doc = new jsPDF() as any;
  const brand = data.brand_name || "Kagiso Hair Suite";

  // 1. Header & Brand Identity
  doc.setFillColor(15, 17, 23); // Deep Charcoal
  doc.rect(0, 0, 210, 40, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.text(brand.toUpperCase(), 20, 25);
  
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.text("OFFICIAL BUSINESS RECEIPT", 20, 32);
  doc.text(`DATE: ${data.date}`, 150, 25);
  doc.text(`REF: #${data.id.slice(0, 8).toUpperCase()}`, 150, 32);

  // 2. Customer & Transaction Details
  doc.setTextColor(40, 40, 40);
  doc.setFontSize(10);
  doc.text("RECIPIENT:", 20, 55);
  doc.setFont("helvetica", "bold");
  doc.text(data.customer_name.toUpperCase(), 20, 62);
  doc.setFont("helvetica", "normal");
  if (data.customer_phone) doc.text(`TEL: ${data.customer_phone}`, 20, 68);

  // 3. Line Items Table
  const tableData = [
    [data.service_name, "1", `R ${data.price.toFixed(2)}`, `R ${data.price.toFixed(2)}`]
  ];

  doc.autoTable({
    startY: 80,
    head: [['SERVICE / PRODUCT', 'QTY', 'UNIT PRICE', 'SUBTOTAL']],
    body: tableData,
    theme: 'grid',
    headStyles: { fillColor: [79, 70, 229], textColor: 255, fontStyle: 'bold' }, // Indigo
    styles: { fontSize: 9, cellPadding: 5 },
    columnStyles: {
      0: { cellWidth: 100 },
      1: { halign: 'center' },
      2: { halign: 'right' },
      3: { halign: 'right' },
    }
  });

  // 4. Financial Summary
  const finalY = (doc as any).lastAutoTable.finalY + 10;
  
  doc.setFont("helvetica", "bold");
  doc.text("TOTAL AMOUNT:", 130, finalY + 10);
  doc.setFontSize(14);
  doc.text(`R ${data.price.toFixed(2)}`, 170, finalY + 10, { align: 'right' });

  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.text("PAYMENT STATUS:", 130, finalY + 20);
  doc.setTextColor(data.payment_status === 'Paid' ? [16, 185, 129] : [245, 158, 11]); // Emerald or Amber
  doc.text(data.payment_status.toUpperCase(), 170, finalY + 20, { align: 'right' });

  // 5. Footer / Legal
  doc.setTextColor(150, 150, 150);
  doc.setFontSize(8);
  doc.text("Thank you for your business. This receipt was automatically generated by Kasi BusinessHub.", 105, 280, { align: 'center' });
  doc.text("For enquiries, contact the Kagiso Hair Suite support team.", 105, 285, { align: 'center' });

  // 6. Output
  doc.save(`Receipt_Kagiso_${data.id.slice(0, 8)}.pdf`);
};
