import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";

interface ReceiptData {
  id: string;
  date: string;
  customer_name: string;
  customer_phone?: string;
  service_name: string;
  price: number;
  payment_status: string;
  brand_name?: string;
}

export const generateProfessionalReceipt = (data: ReceiptData) => {
  const doc = new jsPDF() as any;
  const brand = data.brand_name || "Kagiso Hair Suite";

  // 1. Header & Brand Identity
  doc.setFillColor(15, 17, 23); // Deep Charcoal
  doc.rect(0, 0, 210, 40, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.text(brand.toUpperCase(), 20, 25);
  
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.text("OFFICIAL BUSINESS RECEIPT", 20, 32);
  doc.text(`DATE: ${data.date}`, 150, 25);
  doc.text(`REF: #${data.id.slice(0, 8).toUpperCase()}`, 150, 32);

  // 2. Customer & Transaction Details
  doc.setTextColor(40, 40, 40);
  doc.setFontSize(10);
  doc.text("RECIPIENT:", 20, 55);
  doc.setFont("helvetica", "bold");
  doc.text(data.customer_name.toUpperCase(), 20, 62);
  doc.setFont("helvetica", "normal");
  if (data.customer_phone) doc.text(`TEL: ${data.customer_phone}`, 20, 68);

  // 3. Line Items Table
  const tableData = [
    [data.service_name, "1", `R ${data.price.toFixed(2)}`, `R ${data.price.toFixed(2)}`]
  ];

  autoTable(doc, {
    startY: 80,
    head: [['SERVICE / PRODUCT', 'QTY', 'UNIT PRICE', 'SUBTOTAL']],
    body: tableData,
    theme: 'grid',
    headStyles: { fillColor: [79, 70, 229], textColor: 255, fontStyle: 'bold' }, // Indigo
    styles: { fontSize: 9, cellPadding: 5 },
    columnStyles: {
      0: { cellWidth: 100 },
      1: { halign: 'center' },
      2: { halign: 'right' },
      3: { halign: 'right' },
    }
  });

  // 4. Financial Summary
  const rawY = (doc as any).lastAutoTable?.finalY;
  const tableY = typeof rawY === 'number' && !isNaN(rawY) ? rawY : 110;
  const finalY = tableY + 10;
  
  doc.setFont("helvetica", "bold");
  doc.text("TOTAL AMOUNT:", 130, finalY + 10);
  doc.setFontSize(14);
  doc.text(`R ${data.price.toFixed(2)}`, 170, finalY + 10, { align: 'right' });

  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.text("PAYMENT STATUS:", 130, finalY + 20);
  doc.setTextColor(data.payment_status === 'Paid' ? [16, 185, 129] : [245, 158, 11]); // Emerald or Amber
  doc.text(data.payment_status.toUpperCase(), 170, finalY + 20, { align: 'right' });

  // 5. Footer / Legal
  doc.setTextColor(150, 150, 150);
  doc.setFontSize(8);
  doc.text("Thank you for your business. This receipt was automatically generated by Kasi BusinessHub.", 105, 280, { align: 'center' });
  doc.text("For enquiries, contact the Kagiso Hair Suite support team.", 105, 285, { align: 'center' });

  // 6. Output
  doc.save(`Receipt_Kagiso_${data.id.slice(0, 8)}.pdf`);
};

export const generateHistoryReport = (gigs: any[], period: string, brand: string) => {
  const doc = new jsPDF() as any;

  // 1. Header
  doc.setFillColor(15, 17, 23);
  doc.rect(0, 0, 210, 40, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.text((brand || "Kagiso Hair Suite").toUpperCase(), 20, 25);
  
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.text("COMPLETED GIGS HISTORY REPORT", 20, 32);
  doc.text(`PERIOD: ${period.toUpperCase()}`, 150, 25);
  doc.text(`GENERATED: ${new Date().toLocaleDateString()}`, 150, 32);

  // 2. Data Table
  const tableData = gigs.map(gig => [
    new Date(gig.slot_start).toLocaleDateString(),
    gig.customer_name,
    gig.products?.name || "Bespoke",
    `R ${gig.products?.price?.toFixed(2) || '0.00'}`
  ]);

  const totalRevenue = gigs.reduce((sum, current) => sum + (current.products?.price || 0), 0);
  tableData.push(["", "", "TOTAL REVENUE:", `R ${totalRevenue.toFixed(2)}`]);

  autoTable(doc, {
    startY: 50,
    head: [['DATE', 'CLIENT', 'SERVICE', 'PRICE']],
    body: tableData,
    theme: 'grid',
    headStyles: { fillColor: [79, 70, 229], textColor: 255, fontStyle: 'bold' },
    styles: { fontSize: 9, cellPadding: 5 },
    columnStyles: {
      0: { cellWidth: 40 },
      1: { cellWidth: 60 },
      2: { cellWidth: 60 },
      3: { halign: 'right' },
    },
    didParseCell: function(data: any) {
        if (data.row.index === tableData.length - 1) {
            data.cell.styles.fontStyle = 'bold';
            data.cell.styles.textColor = [16, 185, 129];
        }
    }
  });

  // 3. Output
  doc.save(`History_Report_${period}_KHD.pdf`);
};
